# generated by datamodel-codegen:
#   filename:  model.json
#   timestamp: 2021-04-11T02:34:32+00:00

from __future__ import annotations

from typing import List, Optional
from uuid import UUID

from pydantic import BaseModel, Field


class User(BaseModel):
    discord_id: Optional[UUID] = None
    username: Optional[str] = None


class Model(BaseModel):
    data: Optional[List[User]] = Field(None, description='An array of user records')
    total: Optional[float] = Field(None, description='Total number of records')
    has_more: Optional[bool] = Field(
        None, description='Boolean indicating if there are more records.'
    )

    def __str__(self):
        return f"<{len(self.data)} Users>"
